### ISSUE TITLE
I suppose we should use fmt.Printf(...) instead of fmt.Sprintf(...) ^_^

### ISSUE THREAD

**Issue by Alex-toughman** [wanghaoran1988/openshift-client-go-example#1]
https://github.com/wanghaoran1988/openshift-client-go-example/blob/0d7be8d41fdd1008505efcb6c3b15939016c539b/main.go#L53

**Comment by wanghaoran1988** [comment]
@onecool2 Good catch, feel free to open a pull request, thanks
